"use client";

import { motion } from "framer-motion";
import { BarChart3, Clock3, FlaskConical, MailCheck, Radar, Reply, Send, Sparkles, TrendingUp } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { formatPercent } from "@/lib/utils";
import type { AnalyticsSnapshot } from "@/types/app";

export function AnalyticsClient({ analytics }: { analytics: AnalyticsSnapshot }) {
  const stats = analytics.totals;
  const personal = analytics.personalInsights;

  return (
    <div className="space-y-6">
      <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="rounded-[32px] border border-white/10 bg-black/30 p-8 backdrop-blur-xl">
        <Badge className="border-primary/20 bg-primary/10 text-primary">Analytics</Badge>
        <h1 className="mt-4 text-4xl font-bold text-white">Measure the full recruiter funnel from first send to reply rate.</h1>
        <p className="mt-3 max-w-3xl text-white/60">Track sent volume, open performance, response rate, and campaign-level health without leaving the product. This page summarizes the ATS activity generated by every campaign.</p>
      </motion.div>

      <div className="grid gap-4 xl:grid-cols-4">
        <Card>
          <CardHeader>
            <CardDescription>Total emails sent</CardDescription>
            <CardTitle className="text-3xl">{personal.totalEmailsSent}</CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader>
            <CardDescription>Response rate</CardDescription>
            <CardTitle className="text-3xl">{formatPercent(personal.responseRate)}</CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader>
            <CardDescription>Best time to send</CardDescription>
            <CardTitle className="text-xl">{personal.bestTimeToSend}</CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader>
            <CardDescription>Avg reply probability</CardDescription>
            <CardTitle className="text-3xl">{Math.round(personal.averageReplyProbability)}/100</CardTitle>
          </CardHeader>
        </Card>
      </div>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">
        {[
          { label: "Recruiters", value: stats.recruiters, icon: Radar },
          { label: "Sent", value: stats.sent, icon: Send },
          { label: "Opened", value: stats.opened, icon: MailCheck },
          { label: "Replied", value: stats.replied, icon: Reply },
          { label: "Failed", value: stats.failed, icon: BarChart3 }
        ].map((item) => {
          const Icon = item.icon;
          return (
            <Card key={item.label}>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardDescription>{item.label}</CardDescription>
                  <div className="rounded-2xl bg-primary/10 p-2 text-primary">
                    <Icon className="h-4 w-4" />
                  </div>
                </div>
                <CardTitle className="text-3xl">{item.value}</CardTitle>
              </CardHeader>
            </Card>
          );
        })}
      </div>

      <div className="grid gap-6 xl:grid-cols-[1.05fr_0.95fr]">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2"><TrendingUp className="h-5 w-5 text-primary" />Personal Insights Dashboard</CardTitle>
            <CardDescription>High-signal guidance pulled from your best message, timing data, and current funnel performance.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="rounded-[24px] border border-white/10 bg-white/5 p-5">
              <div className="flex items-center gap-2 text-sm text-white/55">
                <Sparkles className="h-4 w-4 text-primary" />
                Best performing message
              </div>
              <p className="mt-3 text-base font-semibold text-white">{personal.bestPerformingMessage ?? "No clear winner yet"}</p>
            </div>
            <div className="grid gap-3 md:grid-cols-2">
              <div className="rounded-[24px] border border-white/10 bg-white/5 p-5">
                <div className="flex items-center gap-2 text-sm text-white/55"><Clock3 className="h-4 w-4 text-primary" />Best time to send</div>
                <p className="mt-3 text-base font-semibold text-white">{personal.bestTimeToSend}</p>
              </div>
              <div className="rounded-[24px] border border-white/10 bg-white/5 p-5">
                <div className="flex items-center gap-2 text-sm text-white/55"><BarChart3 className="h-4 w-4 text-primary" />Reply probability</div>
                <p className="mt-3 text-base font-semibold text-white">{Math.round(personal.averageReplyProbability)}/100</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2"><MailCheck className="h-5 w-5 text-primary" />Why You’re Not Getting Replies</CardTitle>
            <CardDescription>AI-detected weak patterns in the current outreach mix.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="rounded-[24px] border border-white/10 bg-white/5 p-5 text-sm leading-7 text-white/70">
              {analytics.replyInsights.summary}
            </div>
            <div className="space-y-2">
              {analytics.replyInsights.weakPatterns.map((item) => (
                <div key={item} className="rounded-2xl border border-red-400/15 bg-red-400/10 px-4 py-3 text-sm text-red-100/85">{item}</div>
              ))}
            </div>
            <div className="space-y-2">
              {analytics.replyInsights.recommendations.map((item) => (
                <div key={item} className="rounded-2xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-white/70">{item}</div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-6 xl:grid-cols-[0.46fr_0.54fr]">
        <Card>
          <CardHeader>
            <CardTitle>Pipeline rates</CardTitle>
            <CardDescription>These live percentages help you understand whether your deliverability and messaging are moving in the right direction.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            {[
              { label: "Open rate", value: analytics.openRate },
              { label: "Response rate", value: analytics.responseRate },
              { label: "Pending queue share", value: stats.sent + stats.pending > 0 ? (stats.pending / (stats.sent + stats.pending)) * 100 : 0 }
            ].map((metric) => (
              <div key={metric.label} className="space-y-2">
                <div className="flex items-center justify-between text-sm text-white/60">
                  <span>{metric.label}</span>
                  <span>{formatPercent(metric.value)}</span>
                </div>
                <Progress value={metric.value} />
              </div>
            ))}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Campaign health snapshot</CardTitle>
            <CardDescription>Send progress, reply rates, and failure counts by campaign.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {analytics.campaignHealth.map((campaign) => (
              <div key={campaign.id} className="rounded-[24px] border border-white/10 bg-white/5 p-5">
                <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                  <div>
                    <p className="font-semibold text-white">{campaign.name}</p>
                    <p className="text-sm text-white/45">Sent {campaign.sentCount} • Failed {campaign.failedCount}</p>
                  </div>
                  <div className="flex items-center gap-2 text-sm text-white/55">
                    <span>Reply rate {formatPercent(campaign.replyRate)}</span>
                  </div>
                </div>
                <div className="mt-4 space-y-2">
                  <div className="flex items-center justify-between text-sm text-white/55">
                    <span>Progress</span>
                    <span>{campaign.sendProgress}%</span>
                  </div>
                  <Progress value={campaign.sendProgress} />
                </div>
              </div>
            ))}
            {analytics.campaignHealth.length === 0 ? <p className="text-white/50">No campaigns have been created yet.</p> : null}
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2"><FlaskConical className="h-5 w-5 text-primary" />A/B Test Performance</CardTitle>
          <CardDescription>Compare live response rates between the last two generated email variants.</CardDescription>
        </CardHeader>
        <CardContent>
          {analytics.activeAbTest ? (
            <div className="grid gap-4 md:grid-cols-2">
              {analytics.activeAbTest.variants.map((variant) => (
                <div key={variant.label} className="rounded-[24px] border border-white/10 bg-white/5 p-5">
                  <div className="flex items-center justify-between gap-3">
                    <p className="font-semibold text-white">Variant {variant.label}</p>
                    <Badge className={analytics.activeAbTest?.winner === variant.label ? "border-primary/20 bg-primary/10 text-primary" : "border-white/10 bg-white/5 text-white"}>
                      {formatPercent(variant.responseRate)}
                    </Badge>
                  </div>
                  <p className="mt-3 text-sm font-medium text-white/85">{variant.subject}</p>
                  <p className="mt-3 text-sm leading-7 text-white/55">Assigned {variant.assignedCount} · Replies {variant.replyCount}</p>
                  <div className="mt-4">
                    <Progress value={variant.responseRate} />
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <p className="text-white/50">No A/B test has been generated yet.</p>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
